### ISSUE TITLE
after updating from 0.14.0 to 0.15.2 xiaomi eycare2 did not work and stops homebridge with error

### ISSUE THREAD

**Issue by Smart71** [aholstenson/miio#102]
[2018-1-25 17:50:08] [Eyecare2] Initializing MiPhilipsLightPlatform platform...
[2018-1-25 17:50:08] [Eyecare2] [MiPhilipsLightPlatform][INFO]********************************************************************
[2018-1-25 17:50:08] [Eyecare2] [MiPhilipsLightPlatform][INFO]          MiPhilipsLightPlatform v0.2.2 By YinHang
[2018-1-25 17:50:08] [Eyecare2] [MiPhilipsLightPlatform][INFO] GitHub: https://github.com/YinHangCode/homebridge-mi-philips-light 
[2018-1-25 17:50:08] [Eyecare2] [MiPhilipsLightPlatform][INFO]                                                QQ Group: 107927710 
[2018-1-25 17:50:08] [Eyecare2] [MiPhilipsLightPlatform][INFO]********************************************************************
[2018-1-25 17:50:08] [Eyecare2] [MiPhilipsLightPlatform][INFO]start success...

/usr/local/lib/node_modules/homebridge-mi-philips-light/Devices/MiPhilipsTableLamp2.js:16
    this.device = new miio.Device({
                  ^
TypeError: miio.Device is not a constructor
    at new MiPhilipsTableLamp2 (/usr/local/lib/node_modules/homebridge-mi-philips-light/Devices/MiPhilipsTableLamp2.js:16:19)
    at MiPhilipsLightPlatform.accessories (/usr/local/lib/node_modules/homebridge-mi-philips-light/index.js:91:21)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

**Comment by aholstenson** [comment]
Thanks for opening an issue! This is an issue with the homebridge-plugin you are using. It needs to be updated to work with miio 0.15.x as 0.15 is a major rewrite of the library. For now you can install the old version of miio by using `miio@0.14.1` together with `npm install`.
