### ISSUE TITLE
TypeError: miio.createDevice is not a function

### ISSUE THREAD

**Issue by jerryngm** [aholstenson/miio#105]
Hi,

I'm trying to run this plugin however i got the following error. Do you have any clue how I can resolve it? thank you!
https://github.com/bazingaterry/homebridge-xiaomi-air-purifier

[2018-1-25 13:54:59] [Air Purifier] Initializing XiaoMiAirPurifier accessory...
/usr/lib/node_modules/homebridge-xiaomi-air-purifier/index.js:106
var device = miio.createDevice({
^

TypeError: miio.createDevice is not a function
at XiaoMiAirPurifier.discover (/usr/lib/node_modules/homebridge-xiaomi-air-purifier/index.js:106:27)
at new XiaoMiAirPurifier (/usr/lib/node_modules/homebridge-xiaomi-air-purifier/index.js:99:10)
at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:275:29)
at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object. (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)

**Comment by aholstenson** [comment]
Thanks for opening an issue! The error is due to changes in this library in version 0.15.x and needs to be fixed by the Homebridge-plugin.

My understanding is that you can work around this issue by installing `miio@0.14.2` locally.

As this isn't a bug in this library, I'm going to close this issue, but if you haven't already take some time to report it to the Homebridge-plugin as well. Thanks!
