### ISSUE TITLE
Vaccum - that.device.activateCharging() - no return to charge with 2nd Generation

### ISSUE THREAD

**Issue by nicoh88** [aholstenson/miio#130]
Hello @aholstenson,

i write currently an new Xiaomi Vaccum Plugin for Homebridge with with miio >= 0.15.6.

`that.device.activateCharging();` works with 1st Generation (stop+return to charge). With the 2nd Generation, he stops, but **not** back to charge. 

With miio 0.14.1 it works for both.

**Can you fix this?**

Thanks, 
Nico

**Comment by aholstenson** [comment]
Thanks for opening an issue! What does the V2 vacuum return for the first call to `stop`?

**Comment by nicoh88** [comment]
Good question. How do I get the exit code from miio via homebridge?

`DEBUG=miio\*,thing\*`?

**Comment by nicoh88** [comment]
That was informative. :)

**Xiaomi Mi Robot V1**
```
homebridge[10145]: [2018-3-28 10:48:57] [Staubsauger OG Bad] ACTION | Stop cleaning and go to charge.
homebridge[10145]: 2018-03-28T08:48:57.520Z thing:miio:74167768 -> (5) {"method":"app_stop","params":[],"id":17}
...
homebridge[10145]: 2018-03-28T08:48:57.528Z thing:miio:74167768 <- Message: `{"result":0,"id":17}`
homebridge[10145]: 2018-03-28T08:48:57.529Z thing:miio:74167768 -> (5) {"method":"app_charge","params":[],"id":18}
...
homebridge[10145]: 2018-03-28T08:48:57.536Z thing:miio:74167768 <- Message: `{"result":0,"id":18}`
homebridge[10145]: 2018-03-28T08:48:58.537Z thing:miio:74167768 -> (5) {"method":"get_status","params":[],"id":19}
...
homebridge[10145]: 2018-03-28T08:48:58.540Z thing:miio:74167768 -> (5) {"method":"get_consumable","params":[],"id":20}
...
homebridge[10145]: 2018-03-28T08:48:58.561Z thing:miio:74167768 <- Message: `{"result":[{"msg_ver":6,"msg_seq":943,"state":3,"battery":100,"clean_time":0,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":60,"dnd_enabled":0}],"id":19}`
...
homebridge[10145]: 2018-03-28T08:48:58.564Z thing:miio:74167768 <- Message: `{"result":[{"main_brush_work_time":366756,"side_brush_work_time":366756,"filter_work_time":366756,"sensor_dirty_time":252243}],"id":20}`
homebridge[10145]: 2018-03-28T08:48:58.565Z thing:miio:74167768 Property state changed from cleaning to waiting
```

**Xiaomi Roborock S50**
```
homebridge[10145]: [2018-3-28 10:47:27] [Staubsauger EG Flur] ACTION | Stop cleaning and go to charge.
homebridge[10145]: 2018-03-28T08:47:27.474Z thing:miio:82798803 -> (5) {"method":"app_stop","params":[],"id":11}
...
homebridge[10145]: 2018-03-28T08:47:27.486Z thing:miio:82798803 <- Message: `{"result":["ok"],"id":11}`
homebridge[10145]: (node:10145) UnhandledPromiseRejectionWarning: Error: Could not complete call to device
homebridge[10145]:     at checkResult (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/devices/vacuum.js:14:9)
homebridge[10145]:     at <anonymous>
homebridge[10145]:     at process._tickCallback (internal/process/next_tick.js:188:7)
homebridge[10145]: (node:10145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Result `{"result":["ok"],"id":11}` vs. `{"result":0,"id":17}`

**Comment by nicoh88** [comment]
@aholstenson 

BTW: With all actions comes:

```
homebridge[18736]: (node:18736) UnhandledPromiseRejectionWarning: Error: Could not complete call to device
homebridge[18736]:     at checkResult (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/miio/lib/devices/vacuum.js:16:9)
homebridge[18736]:     at <anonymous>
homebridge[18736]: (node:18736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withou
```

Because the result at Roborock S50 is "ok", not 0.
I have not noticed yet, as i've just updated from Node6 to Node8.
