### ISSUE TITLE
`miio discover` don't give any output

### ISSUE THREAD

**Issue by akozlov75** [aholstenson/miio#176]
DEBUG=thing* miio discover
 INFO  Discovering devices. Press Ctrl+C to stop.

  thing:miio:80509541 <- Handshake reply: <Buffer c1 03 a6 a1 8c 01 ac 9c 96 a4 b1 d3 7d 0e 36 53> +0ms
  thing:miio:80509541 Using automatic token: c103a6a18c01ac9c96a4b1d37d0e3653 +1ms
  thing:miio:80509541 -> (5) {"method":"miIO.info","params":[],"id":1} +1ms
  thing:miio:80509541 <- Message: `{"result":{"life":856,"cfg_time":0,"token":"c103a6a18c01ac9c96a4b1d37d0e3653","mac":"78:11:DC:DA:CC:E4","fw_ver":"1.4.1_157","hw_ver":"MW300","model":"lumi.gateway.v3","mcu_fw_ver":"0143","wifi_fw_ver":"SD878x-14.76.36.p84-702.1.0-WM","ap":{"rssi":-256,"ssid":".","bssid":"9E:04:1F:CA:02:13"},"netif":{"localIp":"77.158.4.31","mask":"148.111.17.0","gw":"155.2.19.0","gw_mac":""},"mmfree":173920,"otu_stat":[0,0,0,0,0,0],"ott_stat":[0, 0, 0, 0]},"id":1}` +4ms
  thing:miio:80509541 <- Handshake reply: <Buffer c1 03 a6 a1 8c 01 ac 9c 96 a4 b1 d3 7d 0e 36 53> +472ms
  thing:miio:80509541 -> (5) {"method":"get_prop","params":["illumination","rgb"],"id":2} +5s
  thing:miio:80509541 <- Message: `{"result":[611,0],"id":2}` +3ms
  thing:miio:80509541 Property illuminance changed from undefined to 611 +0ms
  thing:miio:80509541 Property rgb changed from undefined to { red: 0, green: 0, blue: 0 } +0ms
  thing:miio:80509541 Property brightness changed from undefined to 0 +1ms
  thing:miio:80509541 -> (5) {"method":"get_lumi_dpf_aes_key","params":[],"id":3} +2ms
  thing:miio:80509541 <- Message: `{"result":["r0u4yjyhqx1npdds"],"id":3}` +29ms
  thing:miio:80509541 DEV BROADCAST -> {"cmd":"whois"} +31ms
  thing:miio:80509541 DEV <- Timeout for whois +1s
  thing:miio:80509541 -> (5) {"method":"get_device_prop","params":["lumi.0","device_list"],"id":4} +1s
  thing:miio:80509541 <- Message: `{"result":["lumi.158d0001e5cccd",52,1,0,5,"lumi.158d00022b6670",19,1,0,3,"lumi.158d0001de6761",53,1,0,3],"id":4}` +3ms
  thing:miio:80509541 DEV -> {"cmd":"read","sid":"158d0001e5cccd"} +6ms
  thing:miio:80509541 DEV -> {"cmd":"read","sid":"158d00022b6670"} +1ms
  thing:miio:80509541 DEV -> {"cmd":"read","sid":"158d0001de6761"} +0ms
  thing:miio:158d0001e5cccd Read via DEV timed out, using fallback API +0ms
  thing:miio:158d00022b6670 Read via DEV timed out, using fallback API +0ms
  thing:miio:158d0001de6761 Read via DEV timed out, using fallback API +0ms
  thing:miio:80509541 -> (5) {"method":"get_device_prop_exp","params":[["lumi.158d0001e5cccd","voltage","status","lux"]],"id":5} +1s
  thing:miio:80509541 -> (5) {"method":"get_device_prop_exp","params":[["lumi.158d00022b6670","voltage","temperature","humidity","pressure"]],"id":6} +1ms
  thing:miio:80509541 -> (5) {"method":"get_device_prop_exp","params":[["lumi.158d0001de6761","voltage","status"]],"id":7} +0ms
  thing:miio:80509541 <- Message: `{"result":[[,,]],"id":5}` +13ms
  thing:miio:80509541 <- Invalid JSON SyntaxError: Unexpected token , in JSON at position 12
    at JSON.parse (<anonymous>)
    at module.exports (/Users/goslow/.nvm/versions/node/v8.12.0/lib/node_modules/miio/lib/safeishJSON.js:10:15)
    at DeviceInfo.onMessage (/Users/goslow/.nvm/versions/node/v8.12.0/lib/node_modules/miio/lib/network.js:367:18)
    at Socket._socket.on (/Users/goslow/.nvm/versions/node/v8.12.0/lib/node_modules/miio/lib/network.js:160:11)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8) +0ms
  thing:miio:80509541 <- Message: `{"result":[["",10000,0,0]],"id":6}` +1ms
  thing:miio:158d00022b6670 Property voltage changed from undefined to  +15ms
  thing:miio:158d00022b6670 Property temperature changed from undefined to 100 +1ms
  thing:miio:158d00022b6670 Property humidity changed from undefined to 0 +0ms
  thing:miio:158d00022b6670 Property atmosphericPressure changed from undefined to 0 +0ms
  thing:miio:80509541 <- Message: `{"result":[[,]],"id":7}` +1ms
  thing:miio:80509541 -> (4) {"method":"get_device_prop_exp","params":[["lumi.158d0001e5cccd","voltage","status","lux"]],"id":107} +2s
  thing:miio:80509541 <- Message: `{"result":[[,,]],"id":107}` +3ms
  thing:miio:80509541 <- Invalid JSON SyntaxError: Unexpected token , in JSON at position 12
    at JSON.parse (<anonymous>)
    at module.exports (/Users/goslow/.nvm/versions/node/v8.12.0/lib/node_modules/miio/lib/safeishJSON.js:10:15)
    at DeviceInfo.onMessage (/Users/goslow/.nvm/versions/node/v8.12.0/lib/node_modules/miio/lib/network.js:367:18)
    at Socket._socket.on (/Users/goslow/.nvm/versions/node/v8.12.0/lib/node_modules/miio/lib/network.js:160:11)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8) +0ms

**Comment by akozlov75** [comment]
In v0.15.6 -> `safeishJSON.js` missing this line `str = str.replace('[,,]', '[null,null,null]');` what fix this issue. Guys, please add it to new release!
