### ISSUE TITLE
error when new install runs miio discover

### ISSUE THREAD

**Issue by cyphjuh** [aholstenson/miio#181]
On Ubuntu 16.04 LTS

/usr/local/lib/node_modules/miio/cli/log.js:8
        info(...args) {
             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/miio/cli/commands/configure.js:3:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by cyphjuh** [comment]
Same error when running on a Synology NAS

**Comment by EngrEric** [comment]
I had same issue when i tried to discover my smart surge, 
Solved it by downloading the Mi home app.
connect it to my home network, 
then run miio discover.
it worked for me

**Comment by cyphjuh** [comment]
Unfortunately I’ve already did that. Otherwise the token could change if you add it afterwards (it’s a roborock s50)

**Comment by Kieera** [comment]
I also encountered this problem.Solved by updating the version of npm and node
