### ISSUE TITLE
Trying to add token to miio but get Address in use :S

### ISSUE THREAD

**Issue by jgarmar** [aholstenson/miio#202]
this is the error I'm getting trying to add a token

dgram.js:581
    throw errnoException(err, 'addMembership');
    ^

Error: addMembership EADDRINUSE
    at Socket.addMembership (dgram.js:581:11)
    at Socket.DeveloperApi.socket.on (/usr/local/lib/node_modules/miio/lib/devices/gateway/developer-api.js:43:19)
    at Socket.emit (events.js:182:13)
    at startListening (dgram.js:128:10)
    at state.handle.lookup (dgram.js:249:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by dmnbi4** [comment]
same problem, but I try "miio discover"
