### ISSUE TITLE
ChuangmiIRPlatform irLearn Learn Failed, Status Unready

### ISSUE THREAD

**Issue by hkccmaster** [aholstenson/miio#235]
i add the mi ir remote plugin and fail doing the first step to learn code, i copy from the log here:

5 10 02:46:47 raspberrypi homebridge[4302]: [2019-5-10 02:46:47] [ChuangmiIRPlatform] [irLearn] Learn Started
5 10 02:46:47 raspberrypi homebridge[4302]: [2019-5-10 02:46:47] [ChuangmiIRPlatform] [irLearn] Learn Failed, Status Unready

i double checked the token and ip, they should be correct, any idea friend?

**Comment by GreatCookie** [comment]
Having the same issue with my devices controlled by the Platform - started about 3 weeks ago as well

[ChuangmiIRPlatform] [Device Name]Projector: Unready

**Comment by FrankYip1020** [comment]
I have this problem too.
here is my message when I start homebridge:
`[2019-7-2 02:07:19] Homebridge is running on port 51826.
Error occurred: { Error: Could not connect to device, token might be wrong
    at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16)
    at <anonymous> code: 'connection-failure', device: null }
Error occurred: { Error: Could not connect to device, token might be wrong
    at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16)
    at <anonymous> code: 'connection-failure', device: null }
Error occurred: { Error: Could not connect to device, token might be wrong
    at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16)
    at <anonymous> code: 'connection-failure', device: null }
Error occurred: { Error: Could not connect to device, token might be wrong
    at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16)
    at <anonymous> code: 'connection-failure', device: null }
Error occurred: { Error: Could not connect to device, token might be wrong
    at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16)
    at <anonymous> code: 'connection-failure', device: null }
Error occurred: { Error: Could not connect to device, token might be wrong
    at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16)
    at <anonymous> code: 'connection-failure', device: null }
Error occurred: { Error: Could not connect to device, token might be wrong
    at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16)
    at <anonymous> code: 'connection-failure', device: null }`
And when I click IR learn
`[2019-7-2 02:08:49] [ChuangmiIRPlatform] [irLearn] Learn Started
[2019-7-2 02:08:49] [ChuangmiIRPlatform] [irLearn] Learn Failed, Status Unready`

**Comment by FrankYip1020** [comment]
> I have this problem too.
> here is my message when I start homebridge:
> `[2019-7-2 02:07:19] Homebridge is running on port 51826. Error occurred: { Error: Could not connect to device, token might be wrong at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16) at <anonymous> code: 'connection-failure', device: null } Error occurred: { Error: Could not connect to device, token might be wrong at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16) at <anonymous> code: 'connection-failure', device: null } Error occurred: { Error: Could not connect to device, token might be wrong at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16) at <anonymous> code: 'connection-failure', device: null } Error occurred: { Error: Could not connect to device, token might be wrong at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16) at <anonymous> code: 'connection-failure', device: null } Error occurred: { Error: Could not connect to device, token might be wrong at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16) at <anonymous> code: 'connection-failure', device: null } Error occurred: { Error: Could not connect to device, token might be wrong at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16) at <anonymous> code: 'connection-failure', device: null } Error occurred: { Error: Could not connect to device, token might be wrong at enrichPromise.promise.then.then.catch.err (/usr/lib/node_modules/miio/lib/network.js:324:16) at <anonymous> code: 'connection-failure', device: null }`
> And when I click IR learn
> `[2019-7-2 02:08:49] [ChuangmiIRPlatform] [irLearn] Learn Started [2019-7-2 02:08:49] [ChuangmiIRPlatform] [irLearn] Learn Failed, Status Unready`

I'm sure the token is right.

**Comment by sebirb** [comment]
Hey there! First time with HomeBridge and Xiaomi Mi Receiver **V2**. The issue came whenever you try to activate the "MyLearn" button in Homekit. I'll paste here the log: (I'm sure the token is right, I have done the process 4 times).

[2020-7-25 22:19:15] [ChuangmiIRPlatform] [irLearn] Learn Started
[2020-7-25 22:19:15] [ChuangmiIRPlatform] [irLearn] Learn Failed, Status Unready
Error occurred: Error: Could not connect to device, token might be wrong
    at C:\Users\Rosa\AppData\Roaming\npm\node_modules\miio\lib\network.js:324:16 {
  code: 'connection-failure',
  device: null

Anyway the other button works properly but when activated shown: 

[2020-7-25 22:26:22] [ChuangmiIRPlatform] [Телевизор]Switch: Unready

Also I was trying it with iOS 14 device but I also tried with an iPhone with iOS13 and MacOS Catalina too.

**Comment by ericwongmusic** [comment]
I cannot activate the plugin successfully on my homebridge config. I consulted hoobs.org, and they replied:


That’s a plugin issue. The developer must add the name of the plugin as the first parameter when registering the platform or accessory. Please open an issue with the plugin developer on their GitHub page

Please kindly fix it!  Thanks!
