### ISSUE TITLE
Catch crypto errors on incoming packets

### ISSUE THREAD

**Issue by Bluebie** [aholstenson/miio#3]
When UDP packets are received, miio should check for failures decrypting the packet, and discard invalid packets, possibly with some debugging api or mode to make these errors visible again. My [homebridge-miio](/Bluebie/homebridge-miio/) instance just crashed inexplicably because of this. I guess some other network app may have sent in to the local port accidentally.

```
crypto.js:157
  var ret = this._handle.final();
                         ^

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (crypto.js:157:26)
    at Packet.set raw [as raw] (homebridge-miio/node_modules/miio/packet.js:98:14)
    at Device._onMessage (homebridge-miio/node_modules/miio/device.js:33:19)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:192:7)
    at UDP.onMessage [as onmessage] (dgram.js:547:8)
```

**Comment by aholstenson** [comment]
Thanks for the report! I've added support for verifying the incoming checksum of packets and added some extra protection for malformed packets. The fixes are available in 0.4.0 that was just pushed to NPM.
