### ISSUE TITLE
Cannot start a discovery

### ISSUE THREAD

**Issue by karlkar** [aholstenson/miio#62]
Hi. I'm having the following problem when trying to run the discovery:
```
pi@raspberrypi:~ $ sudo miio --discover                      

/usr/local/lib/node_modules/miio/cli/index.js:10
const { Browser, Devices } = require('../lib/discovery');
      ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

What's wrong?

**Comment by Bluebie** [comment]
you need a newer version of nodejs

**Comment by aholstenson** [comment]
As mentioned your version of Node seems old. Also you shouldn't need to run `miio` with `sudo`.
